{% set name = "cleverhans" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cleverhans-lab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f30449a2012a3e35470db053c2c30e99d6feb5785d001a42d50509ac1a831f87

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - nose
    - pycodestyle
    - scipy
    - matplotlib-base
    - mnist >=0.2
    - numpy
    - tensorflow-probability
    - joblib

test:
  imports:
    - cleverhans

about:
  home: https://github.com/tensorflow/cleverhans
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: This repository contains the source code for CleverHans, a Python library to benchmark machine learning systems' vulnerability to adversarial examples.
  doc_url: https://pypi.org/project/cleverhans/#description
  dev_url: https://github.com/tensorflow/cleverhans

extra:
  recipe-maintainers:
    - mxr-conda
    - ndmaxar
    - oblute
    - rluria14
